channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python==3.9.7
  - nltk==3.6.7
  - pytorch==1.10.0
  - torchvision
  - torchaudio
  - numpy<=1.24.0
  - pyyaml==6.0
  - pika==1.2.0
  - pydantic==1.9.0
  - python-dotenv==0.20.0
  - git
  - pip<24.1
  - pip:
      - fairseq==0.12.2
      - sentencepiece==0.1.96