channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7.5
  - nltk==3.4.5
  - python-dotenv==0.15.0
  - sentencepiece==0.1.95
  - pyyaml>=5.1
  - numpy>1.19.2
  - portalocker==1.6.0
  - sacrebleu==1.4.14
  - regex==2020.10.15
  - git
  - pip
  - pip:
      - git+https://github.com/pytorch/fairseq.git@d6855baec88f99ac776962027b91d404fe917eea
      - ./nauron/
