channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python==3.8.13
  - mxnet-mkl=1.5.0
  - sentencepiece==0.1.95
  - numpy==1.19.2
  - portalocker==2.3.0
  - nltk==3.7
  - pika==1.3.1
  - pydantic==1.9.0
  - python-dotenv==0.21.0
  - pyyaml==6.0
  - regex
  - pip
#  - pip:
      #sockeye==1.18.106 --no-deps