channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python=3.7.5
  - nltk==3.4.5
  - python-dotenv==0.15.0
  - marshmallow==3.10.0
  - pytorch==1.8.1
  - pyyaml==5.3.1
  - numpy==1.20.3
  - regex==2020.10.15
  - git
  - pip
  - pip:
      - git+https://github.com/pytorch/fairseq.git@d6855baec88f99ac776962027b91d404fe917eea
      - sentencepiece
      - nauron==1.2.2
      - fasttext==0.9.2
