channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7.5
  - mxnet-mkl=1.5.0
  - nltk==3.4.5
  - python-dotenv==0.15.0
  - marshmallow==3.10.0
  - sentencepiece==0.1.95
  - pyyaml>=5.1
  - numpy>1.19.2
  - portalocker==1.6.0
  - regex==2020.10.15
  - pip
  - pip:
    - nauron==1.2.2
