service: translation
workers:
  septilang:
    # Should match the workspace name parameter in the API config
    workspace: default
    # List of all routing keys for this worker, as specified by the routing key of the workspace, separated by dots.
    # When routing uses language keys, all variants of 2-letter (if available) and 3-letter codes should be specified
    # e.g. [ est.ger, est.deu, et.de ]
    routes: [ ]
    # Parameters required by the TranslationWorker
    parameters:
      nmt_model: models/modular_big/modular_big.pt
      spm_prefix: models/modular_big/spm/sp_model
      dict_path: models/modular_big/dicts/
      lid_model: models/modular_big/lid.176.bin
      max_sentences: 10
      max_tokens: 3000
      beam_size: 5
      char_limit: 1000
      languages: { est: et, lav: lv, eng: en, deu: de, ger: de, lit: lt, rus: ru, fin: fi }