models:
  septilang:  # The model name. Used by the flag --model-name to select which model will be loaded by the worker.
    checkpoint_path: models/septilang/modular_model.pt  # The model checkpoint file path
    dict_dir: models/septilang/  # The directory of model dictionary files
    sentencepiece_dir: models/septilang/  # The path to all sentencepiece file directory
    sentencepiece_prefix: sp-model  # The prefix used for sentencepiece model files
    domains:
      - name: general  # The domain name as used by the translation API
        language_pairs:
          # A list of supported language pairs that the worker will handle
          [
            "est-rus", "est-ger", "est-eng", "eng-est", "ger-est", "rus-est",  # comment this line out, if also using the mtee_general model to handle these language pairs
            "est-lit", "est-lav", "est-fin", "est-est",
            "eng-lit", "eng-lav", "eng-fin", "eng-rus", "eng-ger", "eng-eng",
            "ger-lit", "ger-lav", "ger-fin", "ger-rus", "ger-ger", "ger-eng",
            "rus-lit", "rus-lav", "rus-fin", "rus-rus", "rus-ger", "rus-eng",
            "fin-lit", "fin-lav", "fin-fin", "fin-rus", "fin-ger", "fin-eng", "fin-est",
            "lav-lit", "lav-lav", "lav-fin", "lav-rus", "lav-ger", "lav-eng", "lav-est",
            "lit-lit", "lit-lav", "lit-fin", "lit-rus", "lit-ger", "lit-eng", "lit-est"
          ]
    language_codes:
      # A mapping of the standard 3-letter codes used by translation API to language codes used by the model internally.
      { est: et, lav: lv, eng: en, ger: de, lit: lt, rus: ru, fin: fi }
  mtee_general:
    checkpoint_path: models/mtee-general/modular_model.pt
    dict_dir: models/mtee-general/dicts/
    sentencepiece_dir: models/mtee-general/spm/
    sentencepiece_prefix: sp-model
    domains:
      - name: general
        language_pairs: [ "est-rus", "est-ger", "est-eng", "eng-est", "ger-est", "rus-est" ]
    language_codes: { est: et, ger: de, eng: en, rus: ru }
  mtee_legal:
    checkpoint_path: models/mtee-legal/modular_model.pt
    dict_dir: models/mtee-legal/dicts/
    sentencepiece_dir: models/mtee-legal/spm/
    sentencepiece_prefix: sp-model
    domains:
      - name: legal
        language_pairs: [ "est-rus", "est-ger", "est-eng", "eng-est", "ger-est", "rus-est" ]
    language_codes: { est: et, ger: de, eng: en, rus: ru }
  mtee_military:
    checkpoint_path: models/mtee-military/modular_model.pt
    dict_dir: models/mtee-legal/dicts/
    sentencepiece_dir: models/mtee-legal/spm/
    sentencepiece_prefix: sp-model
    domains:
      - name: military
        language_pairs: [ "est-rus", "est-ger", "est-eng", "eng-est", "ger-est", "rus-est" ]
    language_codes: { est: et, ger: de, eng: en, rus: ru }
  mtee_crisis:
    checkpoint_path: models/mtee-crisis/modular_model.pt
    dict_dir: models/mtee-legal/dicts/
    sentencepiece_dir: models/mtee-legal/spm/
    sentencepiece_prefix: sp-model
    domains:
      - name: crisis
        language_pairs: [ "est-rus", "est-ger", "est-eng", "eng-est", "ger-est", "rus-est" ]
    language_codes: { est: et, ger: de, eng: en, rus: ru }
  smugri:
    checkpoint_path: models/smugri
    checkpoint_file: smugri2.pt
    dict_dir: models/smugri/dicts
    dict_path: models/smugri/model_dict.ext.txt
    sentencepiece_path: models/smugri/spm/spm.ext.model
    domains:
      - name: general
        language_pairs: ["en-hu", "en-kpv", "en-liv", "en-mdf", "en-mhr", "en-mns", "en-mrj", "en-myv", "en-no", "en-olo", "en-udm", "et-hu", "et-kpv", "et-liv", "et-mdf", "et-mhr", "et-mns", "et-mrj", "et-myv", "et-no", "et-olo", "et-udm", "fi-hu", "fi-kpv", "fi-liv", "fi-mdf", "fi-mhr", "fi-mns", "fi-mrj", "fi-myv", "fi-no", "fi-olo", "fi-udm", "hu-en", "hu-et", "hu-fi", "hu-kpv", "hu-liv", "hu-lv", "hu-mdf", "hu-mhr", "hu-mns", "hu-mrj", "hu-myv", "hu-no", "hu-olo", "hu-ru", "hu-udm", "kpv-en", "kpv-et", "kpv-fi", "kpv-hu", "kpv-liv", "kpv-lv", "kpv-mdf", "kpv-mhr", "kpv-mns", "kpv-mrj", "kpv-myv", "kpv-no", "kpv-olo", "kpv-ru", "kpv-udm", "liv-en", "liv-et", "liv-fi", "liv-hu", "liv-kpv", "liv-lv", "liv-mdf", "liv-mhr", "liv-mns", "liv-mrj", "liv-myv", "liv-no", "liv-olo", "liv-ru", "liv-udm", "lv-hu", "lv-kpv", "lv-liv", "lv-mdf", "lv-mhr", "lv-mns", "lv-mrj", "lv-myv", "lv-no", "lv-olo", "lv-udm", "mdf-en", "mdf-et", "mdf-fi", "mdf-hu", "mdf-kpv", "mdf-liv", "mdf-lv", "mdf-mhr", "mdf-mns", "mdf-mrj", "mdf-myv", "mdf-no", "mdf-olo", "mdf-ru", "mdf-udm", "mhr-en", "mhr-et", "mhr-fi", "mhr-hu", "mhr-kpv", "mhr-liv", "mhr-lv", "mhr-mdf", "mhr-mns", "mhr-mrj", "mhr-myv", "mhr-no", "mhr-olo", "mhr-ru", "mhr-udm", "mns-en", "mns-et", "mns-fi", "mns-hu", "mns-kpv", "mns-liv", "mns-lv", "mns-mdf", "mns-mhr", "mns-mrj", "mns-myv", "mns-no", "mns-olo", "mns-ru", "mns-udm", "mrj-en", "mrj-et", "mrj-fi", "mrj-hu", "mrj-kpv", "mrj-liv", "mrj-lv", "mrj-mdf", "mrj-mhr", "mrj-mns", "mrj-myv", "mrj-no", "mrj-olo", "mrj-ru", "mrj-udm", "myv-en", "myv-et", "myv-fi", "myv-hu", "myv-kpv", "myv-liv", "myv-lv", "myv-mdf", "myv-mhr", "myv-mns", "myv-mrj", "myv-no", "myv-olo", "myv-ru", "myv-udm", "no-en", "no-et", "no-fi", "no-hu", "no-kpv", "no-liv", "no-lv", "no-mdf", "no-mhr", "no-mns", "no-mrj", "no-myv", "no-olo", "no-ru", "no-udm", "olo-en", "olo-et", "olo-fi", "olo-hu", "olo-kpv", "olo-liv", "olo-lv", "olo-mdf", "olo-mhr", "olo-mns", "olo-mrj", "olo-myv", "olo-no", "olo-ru", "olo-udm", "ru-hu", "ru-kpv", "ru-liv", "ru-mdf", "ru-mhr", "ru-mns", "ru-mrj", "ru-myv", "ru-no", "ru-olo", "ru-udm", "udm-en", "udm-et", "udm-fi", "udm-hu", "udm-kpv", "udm-liv", "udm-lv", "udm-mdf", "udm-mhr", "udm-mns", "udm-mrj", "udm-myv", "udm-no", "udm-olo", "udm-ru"]
    language_codes: {est: et, eng: en, fin: fi, lav: lv, nor: no, hun: hu, rus: ru, kca: kca, koi: koi, kpv: kpv, krl: krl, lud: lud, mdf: mdf, mhr: mhr, mns: mns, mrj: mrj, myv: myv, olo: olo, udm: udm, vep: vep, liv: liv, vro: vro, sma: sma, sme: sme, smn: smn, sms: sms, smj: smj}